/**
 * Signals Panel
 * Displays trading signals generated by the intelligence engine.
 * Listens for `signals-updated` window events and renders the top 5.
 */

import { registerPanel } from './panel-manager';

// ── Types ───────────────────────────────────────────────────────────────────

export interface Signal {
  id: string;
  strategy: 'GEOPOLITICAL' | 'SENTIMENT' | 'MACRO';
  symbol: string;
  direction: 'LONG' | 'SHORT';
  confidence: number; // 0–1
  reasoning: string;
  targetReturn: number; // e.g. 0.15 = 15%
  stopLoss: number;    // e.g. 0.05 = 5% (always positive, applied as loss)
  timestamp: number;
}

// ── Mock data ────────────────────────────────────────────────────────────────

const MOCK_SIGNALS: Signal[] = [
  {
    id: 'sig-001',
    strategy: 'GEOPOLITICAL',
    symbol: 'GLD',
    direction: 'LONG',
    confidence: 0.78,
    reasoning: 'Safe haven demand amid rising CII in Middle East. Conflict convergence detected.',
    targetReturn: 0.15,
    stopLoss: 0.05,
    timestamp: Date.now() - 12 * 60_000,
  },
  {
    id: 'sig-002',
    strategy: 'SENTIMENT',
    symbol: 'EEM',
    direction: 'SHORT',
    confidence: 0.65,
    reasoning: 'GDELT tone score deteriorating across EM Asia. Rolling 4h average at -3.2.',
    targetReturn: 0.08,
    stopLoss: 0.04,
    timestamp: Date.now() - 34 * 60_000,
  },
  {
    id: 'sig-003',
    strategy: 'MACRO',
    symbol: 'TLT',
    direction: 'LONG',
    confidence: 0.71,
    reasoning: 'Yield curve inversion deepening. 2Y-10Y spread at -45bps. Flight to duration.',
    targetReturn: 0.10,
    stopLoss: 0.03,
    timestamp: Date.now() - 58 * 60_000,
  },
];

// ── Helpers ─────────────────────────────────────────────────────────────────

function formatAgo(timestamp: number): string {
  const mins = Math.floor((Date.now() - timestamp) / 60_000);
  if (mins < 60) return `${mins}m ago`;
  return `${Math.floor(mins / 60)}h ago`;
}

// ── DOM builder ──────────────────────────────────────────────────────────────

function buildSignalItem(signal: Signal): HTMLElement {
  const item = document.createElement('div');
  item.className = 'signal-item';
  item.dataset.direction = signal.direction;
  item.dataset.signalId = signal.id;

  if (signal.confidence > 0.7) {
    item.classList.add('signal-high-confidence');
  }

  // Top row: symbol | direction badge | confidence
  const top = document.createElement('div');
  top.className = 'signal-item-top';

  const symbolEl = document.createElement('span');
  symbolEl.className = 'signal-symbol';
  symbolEl.textContent = signal.symbol;

  const dirEl = document.createElement('span');
  dirEl.className = `signal-direction ${signal.direction === 'LONG' ? 'long' : 'short'}`;
  dirEl.textContent = signal.direction === 'LONG' ? '▲ LONG' : '▼ SHORT';

  const confEl = document.createElement('span');
  confEl.className = 'signal-confidence';
  confEl.textContent = `${Math.round(signal.confidence * 100)}%`;

  top.appendChild(symbolEl);
  top.appendChild(dirEl);
  top.appendChild(confEl);

  // Reasoning
  const reasoningEl = document.createElement('div');
  reasoningEl.className = 'signal-reasoning';
  reasoningEl.textContent = signal.reasoning;

  // Meta row: strategy | target | stop | age
  const meta = document.createElement('div');
  meta.className = 'signal-meta';

  const strategyEl = document.createElement('span');
  strategyEl.className = 'signal-strategy';
  strategyEl.textContent = signal.strategy;

  const targetEl = document.createElement('span');
  targetEl.className = 'signal-target';
  targetEl.textContent = `Target: +${(signal.targetReturn * 100).toFixed(1)}%`;

  const stopEl = document.createElement('span');
  stopEl.className = 'signal-stop';
  stopEl.textContent = `Stop: -${(signal.stopLoss * 100).toFixed(1)}%`;

  const ageEl = document.createElement('span');
  ageEl.className = 'signal-age';
  ageEl.textContent = formatAgo(signal.timestamp);

  meta.appendChild(strategyEl);
  meta.appendChild(targetEl);
  meta.appendChild(stopEl);
  meta.appendChild(ageEl);

  // Execute button
  const execBtn = document.createElement('button');
  execBtn.className = 'signal-execute-btn';
  execBtn.textContent = 'Execute Signal';
  execBtn.addEventListener('click', (e) => {
    e.stopPropagation();
    window.dispatchEvent(new CustomEvent('execute-signal', { detail: { signal } }));
    execBtn.textContent = 'Queued ✓';
    execBtn.disabled = true;
    setTimeout(() => {
      execBtn.textContent = 'Execute Signal';
      execBtn.disabled = false;
    }, 3000);
  });

  item.appendChild(top);
  item.appendChild(reasoningEl);
  item.appendChild(meta);
  item.appendChild(execBtn);

  return item;
}

// ── Panel body ───────────────────────────────────────────────────────────────

let signalsListEl: HTMLElement | null = null;
let countEl: HTMLElement | null = null;
let statusEl: HTMLElement | null = null;
let currentSignals: Signal[] = [...MOCK_SIGNALS];

function renderSignals(signals: Signal[]): void {
  if (!signalsListEl || !countEl) return;

  const top5 = [...signals]
    .sort((a, b) => b.confidence - a.confidence || b.timestamp - a.timestamp)
    .slice(0, 5);

  signalsListEl.innerHTML = '';

  if (top5.length === 0) {
    const empty = document.createElement('div');
    empty.className = 'signals-empty';
    empty.textContent = 'No signals generated yet. Intelligence engine is monitoring.';
    signalsListEl.appendChild(empty);
  } else {
    top5.forEach((s) => signalsListEl!.appendChild(buildSignalItem(s)));
  }

  countEl.textContent = `${signals.length} Active Signal${signals.length !== 1 ? 's' : ''}`;
}

function buildSignalsBody(container: HTMLElement): void {
  // Header row
  const headerRow = document.createElement('div');
  headerRow.className = 'signals-header-row';

  countEl = document.createElement('span');
  countEl.className = 'signals-count';
  countEl.textContent = `${currentSignals.length} Active Signals`;

  statusEl = document.createElement('span');
  statusEl.className = 'signals-status';
  statusEl.textContent = 'Monitoring';

  headerRow.appendChild(countEl);
  headerRow.appendChild(statusEl);
  container.appendChild(headerRow);

  // List
  signalsListEl = document.createElement('div');
  signalsListEl.className = 'signals-list';
  container.appendChild(signalsListEl);

  // Render mock data immediately
  renderSignals(currentSignals);

  // Listen for live signal updates
  window.addEventListener('signals-updated', (e: Event) => {
    const { signals } = (e as CustomEvent<{ signals: Signal[] }>).detail;
    currentSignals = signals;
    if (statusEl) statusEl.textContent = 'Live';
    renderSignals(currentSignals);

    // Update panel badge
    const badge = document.querySelector('[data-panel-id="signals"] .panel-badge');
    if (badge) {
      badge.textContent = 'LIVE';
      badge.className = 'panel-badge live';
    }
  });
}

// ── Export ───────────────────────────────────────────────────────────────────

export function initSignalsPanel(): void {
  registerPanel({
    id: 'signals',
    title: 'Trading Signals',
    badge: 'MOCK',
    badgeClass: 'mock',
    defaultCollapsed: false,
    init: buildSignalsBody,
  });
}
